In [7]:
import statistics
data =[2,4,6,8,10,12,14,16,18,20]
data_range=max(data)-min(data)

variance=statistics.variance(data)
mean=statistics.mean(data)
std_dev=statistics.stdev(data)
print(f"data: {data}")
print(f"data range: {data_range}")
print(f"variance: {variance}")
print(f"mean: {mean}")
print(f"standard deviation: {std_dev}")

data: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
data range: 18
variance: 36.666666666666664
mean: 11
standard deviation: 6.0553007081949835


In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a.dtype

dtype('int32')

In [4]:
np.ones(2)

array([1., 1.])

In [5]:
np.zeros(2)

array([0., 0.])

In [7]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.empty(2)

array([7.56599128e-307, 1.60219035e-306])

In [15]:
arr=np.array([2,1,3,8,6,5,7,90])
np.sort(arr)

array([ 1,  2,  3,  5,  6,  7,  8, 90])

In [16]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
arr=np.array([2,1,3,8,6,5,7,90])
np.argsort(arr)

array([1, 0, 2, 5, 4, 6, 3, 7], dtype=int64)

In [3]:
import numpy as np
arr=np.array([5,10,15,20,25])
print(arr[-2])

20


In [5]:
arr=np.array([5,10,15,20,25])
print(arr[:4])

[ 5 10 15 20]


In [13]:
arr=np.array([5,10,15,20])
b=np.expand_dims(arr,axis=1)
b.shape

(4, 1)

In [14]:
arr=np.array([5,10,15,20])
b=np.expand_dims(arr,axis=0)
b.shape

(1, 4)

In [16]:
c=np.copy(arr)
print("Orignal array",arr)
c[0]=99
print("copied array and modified",c)

Orignal array [ 5 10 15 20]
copied array and modified [99 10 15 20]


In [19]:
d=np.append(arr,7)
print("Appended array",d)
f=np.insert(arr,4,1000)
print("inserted array:",f)

Appended array [ 5 10 15 20  7]
inserted array: [   5   10   15   20 1000]


In [28]:
sorted_array=np.sort(c)
print("Sorted array Asc : ",sorted_array)
des=np.flip(sorted_array)
print("Desc : ",des)

Sorted array Asc :  [10 15 20 99]
Desc :  [99 20 15 10]


In [36]:
remove=f[f!=15]
print("REmoved 15",remove)
delete=np.delete(f,3)
print("deleted ",delete)

REmoved 15 [   5   10   20 1000]
deleted  [   5   10   15 1000]


In [43]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.concatenate((arr1,arr2))
print("contacatenate : ",arr3)
arr4=np.array([5,6,7])
arr5=np.concatenate((arr1,arr2,arr3))
print("contacatenate : ",arr5)

contacatenate :  [1 2 3 4 5 6]
contacatenate :  [1 2 3 4 5 6 1 2 3 4 5 6]


In [54]:
array=np.array([100,200,300,400,500])
print("orignal array : ",array)
copied=np.copy(array)
copied[-1]=999
print("Copied array",copied)
array=np.append(array,[700,900])
print("Appended array",array)
array=np.insert(array,1,250)
print("inserted array:",array)
sorted_array=np.sort(array)
print("Sorted array Asc : ",sorted_array)
splited=np.split(array,2)
print("splited array",splited)





orignal array :  [100 200 300 400 500]
Copied array [100 200 300 400 999]
Appended array [100 200 300 400 500 700 900]
inserted array: [100 250 200 300 400 500 700 900]
Sorted array Asc :  [100 200 250 300 400 500 700 900]
splited array [array([100, 250, 200, 300]), array([400, 500, 700, 900])]
